"""We set the database

Revision ID: 4f5107d8b105
Revises: 
Create Date: 2024-10-30 14:36:01.127091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5107d8b105'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('teacher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('cnic', sa.String(length=13), nullable=False),
    sa.Column('phone_no', sa.String(length=11), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('otp', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('cnic'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('assignment',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('graded', sa.Boolean(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('ta',
    sa.Column('ta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('cnic', sa.String(length=13), nullable=False),
    sa.Column('phone_no', sa.String(length=11), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['head_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('ta_id'),
    sa.UniqueConstraint('cnic'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('function',
    sa.Column('function_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('docstring', sa.String(length=2000), nullable=True),
    sa.Column('parameters', sa.String(length=2000), nullable=True),
    sa.Column('func_name', sa.String(length=200), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.assignment_id'], ),
    sa.PrimaryKeyConstraint('function_id')
    )
    op.create_table('test_functions',
    sa.Column('func_param_rel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['function.function_id'], ),
    sa.PrimaryKeyConstraint('func_param_rel_id')
    )
    op.create_table('expected_value',
    sa.Column('expected_value_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('func_param_rel_id', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['func_param_rel_id'], ['test_functions.func_param_rel_id'], ),
    sa.PrimaryKeyConstraint('expected_value_id')
    )
    op.create_table('parameter',
    sa.Column('param_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('func_param_rel_id', sa.Integer(), nullable=True),
    sa.Column('parameter', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['func_param_rel_id'], ['test_functions.func_param_rel_id'], ),
    sa.PrimaryKeyConstraint('param_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter')
    op.drop_table('expected_value')
    op.drop_table('test_functions')
    op.drop_table('function')
    op.drop_table('ta')
    op.drop_table('assignment')
    op.drop_table('teacher')
    # ### end Alembic commands ###
